### ISSUE TITLE
Supported source version 'RELEASE_7' error

### ISSUE THREAD

**Issue by twiz911** [thilko/gradle-springdoc-plugin#2]
Hi

I am using Java 1.8. When running

gradle generateSpringDoc

I get the error

:transaction:generateSpringDocwarning: Supported source version 'RELEASE_7' from annotation processor 'com.thilko.springdoc.SpringAnnotationProcessor' less than -source '1.8'

**Comment by twiz911** [comment]
I changed to Java 1.7 (which is not a long term solution) and the build passes. However, I only get a css file generated in the buildFolder.

**Comment by thilko** [comment]
Hi,

i released a new version (0.3) and updated the supported source version to 1.8.

Actually I can´t reproduce the issue with missing index.html file here, could you give it a try? If the error still exists I will investigate in it next week.

**Comment by twiz911** [comment]
Thanks. I tried

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "com.thilko.spring:gradle-springdoc-plugin:0.3"
    }
}

apply plugin: 'springdoc'

but now I get the error

10:22:52.912 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
10:22:52.913 [ERROR] [org.gradle.BuildExceptionReporter]
10:22:52.913 [ERROR] [org.gradle.BuildExceptionReporter] \* What went wrong:
10:22:52.913 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':transaction'.
10:22:52.913 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':transaction:springdoc'.
10:22:52.913 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not resolve com.thilko.spring:gradle-springdoc-plugin:0.2.SNAPSHOT.

I'm not sure why it is trying to find com.thilko.spring:gradle-springdoc-plugin:0.2.SNAPSHOT ?

**Comment by thilko** [comment]
My fault. The evil duplication I´ve to remove... :-| I´ve uploaded a 0.3.1 version. This should fix at least the java 1.8 issue. Sorry for inconvinience.

**Comment by twiz911** [comment]
Thanks, it now builds.

However, I still just only get a springdoc.css file in the build/springdoc folder containing:

.panel-default>.panel-heading {
    background-color: #FFFFE3;
}

.methodColumn{
    width: 10%;
}

.sidebar {
    margin: 20px 0 0 20px;
}

.sidebar ul > li > a {
    text-decoration: none;
    margin: 1px auto 0 15px;
}

.content {
    margin: 20px 0 0 0;
}

I can't see any obvious errors when running with --debug

**Comment by thilko** [comment]
Maybe I´ve found the issue. Please could you run the spring doc task with --debug:

```
gradle generateSpringDoc --debug
```

and search for the message:

```
15:10:48.767 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -d C:\cim\code\ithaca\ithaca\build -g -s <SOME_PATH> -proc:only -processor com.thilko.springdoc.SpringAnnotationProcessor
```

The <SOME_PATH> argument is the output directory for the annotation processor. As far as I see that is a wrong directory. I have a project where the same issue has occured and when I look into the given directory the html and css is generated. 

I will fix that.

**Comment by twiz911** [comment]
Hi

I don't see that line at all. I am using a gradle wrapper - could that be the problem?

Thanks

**Comment by thilko** [comment]
Mh, I changed the call to gradle wrapper and I have the output too. Do you have debug logs at all? Could you attach them, maybe I can find the issue.

BTW, I could reproduce the issue when I have subprojects. In that case the files are created in the build directory of the subproject and the css in the main build dir. Do you have subprojects configured?

I will change to location of the generated files. Thx for your patience!

**Comment by twiz911** [comment]
Yes I have a sub project. I've tried adding springdoc in the main build.gradle but always get the error

Plugin with id 'springdoc' not found

I'm not a gradle expert so haven't been able to resolve this yet.

Putting springdoc in the sub project build.gradle I only get the CSS file generated in the build directory of the sub project.

**Comment by thilko** [comment]
Could you attach the resulting debug log file and the gradle call? I think I could find the issue with it. 

In the meanwhile I´ve release 0.4. With that version the index.html and springdoc.css is created directly in buildDir of the current project - which could be a subproject.

So when springbok is included in projectA/subProjectB, the files are created in projectA/subProjectB/build.

**Comment by twiz911** [comment]
I still cannot get it to run when the Gradle buildscript is in the root build.gradle with the error

Plugin with id 'springdoc' not found.

Putting the buildscript in our sub project I now get the CSS file only directly in the buildDir - still no index.html

Attached is the Gradle log.

**Comment by twiz911** [comment]
`
11:40:28.575 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :content:generateSpringDoc (Thread[main,5,main]) started.
11:40:28.575 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :content:generateSpringDoc
11:40:28.576 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':content:generateSpringDoc'
11:40:28.578 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':content:generateSpringDoc' is up-to-date
11:40:28.616 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':content:generateSpringDoc' (up-to-date check took 0.038 secs) due to:
  Output file c:\content\build\dependency-cache has changed.
11:40:28.616 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':content:generateSpringDoc'.
11:40:28.617 [INFO] [org.gradle.api.internal.changedetection.changes.RebuildIncrementalTaskInputs] All input files are considered out-of-date for incremental task ':content:generateSpringDoc'.
11:40:28.622 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -d c:\content\build -g -s c:\content\build -proc:only -processor com.thilko.springdoc.SpringAnnotationProcessor -classpath c:\contentapi\build\libs\contentapi-1.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-core\0.7.0\1bdf635d27892eb6ad084269a1b44d6dbed82470\dropwizard-core-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-context\4.0.5.RELEASE\98cd9a4b8bb0c695c0cfcc204cf804f433851cfe\spring-context-4.0.5.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-beans\4.0.5.RELEASE\11e00022f109653ee0dbe16b59c26e19bd90fa08\spring-beans-4.0.5.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-core\4.0.5.RELEASE\cce94116431b5a1384d58316a4090bbe7718fd5a\spring-core-4.0.5.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-web\4.0.5.RELEASE\1819f6d4ab65fb33e19c492d5c5aa21396e42b3f\spring-web-4.0.5.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.squareup.retrofit\retrofit\1.5.1\266695d62b6df0e1176af2be3634bcd0837d4fbd\retrofit-1.5.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.squareup.retrofit\converter-jackson\1.5.1\61f46da65f0863e2606de2912cbd735972813a40\converter-jackson-1.5.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.github.tomakehurst\wiremock\1.46\25d5c09969efde4841a09fea473d216c64d7d2ce\wiremock-1.46.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-util\0.7.0\2369b9f2fa172e181b860a16aa59a345f7b45f0\dropwizard-util-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-jackson\0.7.0\c0f2e5b5b27b0faa3358967d4ad629175f93ef8b\dropwizard-jackson-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-validation\0.7.0\f86c5f915217f346856c44d40e469b9c468c6ecd\dropwizard-validation-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-configuration\0.7.0\8fd46e786044750cb336f7e527fea6fb0d6428e4\dropwizard-configuration-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-logging\0.7.0\354240a2abd66064c2ef5c09892b2c0b72102f8\dropwizard-logging-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-metrics\0.7.0\2f0653894625668759d4165f74468d100ce2fb48\dropwizard-metrics-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-jersey\0.7.0\8ec458b711e2911707076852827ea8bb908360b\dropwizard-jersey-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-servlets\0.7.0\7af37135230ddafeb92f41ba9f145a76077eb27\dropwizard-servlets-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-jetty\0.7.0\f6e0c1e6b9190ace42fcd9cf935434d6c799a068\dropwizard-jetty-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\io.dropwizard\dropwizard-lifecycle\0.7.0\4af4210bc89fd1f735313dc1e54c0b7386001031\dropwizard-lifecycle-0.7.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-core\3.0.1\1e98427c7f6e53363b598e2943e50903ce4f3657\metrics-core-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-jvm\3.0.1\719d06ca6f87fac3a59cf5cc417e0930ef4ebb3f\metrics-jvm-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-servlets\3.0.1\56c952f185446fb4fc94df336e171bfa207afad7\metrics-servlets-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-healthchecks\3.0.1\bec37e61ebe40bf0f52f3fc8b7df57b5c1773682\metrics-healthchecks-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\net.sourceforge.argparse4j\argparse4j\0.4.3\f4c256934d79940477a35b6c4c182b47ee5f0a6f\argparse4j-0.4.3.jar;C:\Users\defaultUser\.m2\repository\org\eclipse\jetty\orbit\javax.servlet\3.0.0.v201112011016\javax.servlet-3.0.0.v201112011016.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty.toolchain.setuid\jetty-setuid-java\1.0.2\4dc7fca46ac6badff4336c574b2c713ac3e40f73\jetty-setuid-java-1.0.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-aop\4.0.5.RELEASE\d22abbbba78f7c8854fc39346cc99362272c5c90\spring-aop-4.0.5.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-expression\4.0.5.RELEASE\d7ddbc320c31c15cb3612ed64607e181c3b2d851\spring-expression-4.0.5.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.1.3\f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f\commons-logging-1.1.3.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.2.4\a60a5e993c98c864010053cb901b7eab25306568\gson-2.2.4.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\net.sf.jopt-simple\jopt-simple\4.3\88ffca34311a6564a98f14820431e17b4382a069\jopt-simple-4.3.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\xmlunit\xmlunit\1.5\7789cef5caffdecab50fd6099535ad2bc2e98044\xmlunit-1.5.jar;C:\Users\defaultUser\.m2\repository\org\mortbay\jetty\jetty\6.1.26\jetty-6.1.26.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.skyscreamer\jsonassert\1.2.1\def60cc43a10979c25813d43a855cff2849ef8bd\jsonassert-1.2.1.jar;C:\Users\defaultUser\.m2\repository\log4j\log4j\1.2.16\log4j-1.2.16.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.jayway.jsonpath\json-path\0.8.1\fbcad75a02160def33c4359b24015cca2d91ccce\json-path-0.8.1.jar;C:\Users\defaultUser\.m2\repository\org\apache\httpcomponents\httpclient\4.2.3\httpclient-4.2.3.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\junit\junit-dep\4.10\64417b3bafdecd366afa514bd5beeae6c1f85ece\junit-dep-4.10.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\2.0.3\5871fb60dc68d67da54a663c3fd636a10a532948\jsr305-2.0.3.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\joda-time\joda-time\2.3\56498efd17752898cfcc3868c1b6211a07b12b8f\joda-time-2.3.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.datatype\jackson-datatype-guava\2.3.2\cbc44a9367a6c87119d805b713715954e8cb9fb0\jackson-datatype-guava-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.module\jackson-module-afterburner\2.3.2\82b12dc1caf8ae1058352c66976bb45fc1c85e70\jackson-module-afterburner-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.datatype\jackson-datatype-joda\2.3.2\b415fe55a6bf6d7f86771bcbd4adfa60c2d5f228\jackson-datatype-joda-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.1.1\19e1e2be2670b33c5dcc835550527028dddddcd1\logback-classic-1.1.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.hibernate\hibernate-validator\5.0.2.Final\4495f14eb4f4dcfdd7b6116ee7468d08e589f800\hibernate-validator-5.0.2.Final.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.glassfish.web\javax.el\2.2.6\232abfe1f919127e9cfcd6e4e2c6324bb394535\javax.el-2.2.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.dataformat\jackson-dataformat-yaml\2.3.2\38610b020b028895f116d63ce2f6f31170b693b\jackson-dataformat-yaml-2.3.2.jar;C:\Users\defaultUser\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-logback\3.0.1\8de43adfffb3fe8cf380674877ab5d2782f7f0bf\metrics-logback-3.0.1.jar;C:\Users\defaultUser\.m2\repository\org\slf4j\slf4j-api\1.7.6\slf4j-api-1.7.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.slf4j\jul-to-slf4j\1.7.6\322e2af1694ccc75d33f4d11216c852121d8fefd\jul-to-slf4j-1.7.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.1.1\6d9866eb3f38b66530d7b1d41526228df3e9d963\logback-core-1.1.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.slf4j\log4j-over-slf4j\1.7.6\a6a9bc4e71ba7b490235a8f2294ec7dd03bf370b\log4j-over-slf4j-1.7.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-util\9.0.7.v20131107\93a606c83b047e8855eb3af68c335e60fa757367\jetty-util-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.sun.jersey\jersey-core\1.18.1\4f97b0f85a881d3b3478f99a17df7bd258b9d626\jersey-core-1.18.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.sun.jersey\jersey-server\1.18.1\6e4e4fb491ea360a0f4d672729224cbbb9cb456d\jersey-server-1.18.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.sun.jersey\jersey-servlet\1.18.1\ecec31589375845cbd42e75c32b64a1475c44bb4\jersey-servlet-1.18.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-jersey\3.0.1\7f11dd97556e2bb0d6011e79914cad6b65873d9d\metrics-jersey-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.jaxrs\jackson-jaxrs-json-provider\2.3.2\8e635e82db2437804e19e746f460392d791856cf\jackson-jaxrs-json-provider-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-jetty9\3.0.1\d4e5c51f4b963f7d872a68717966cd121815d514\metrics-jetty9-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-server\9.0.7.v20131107\682ae23f9e4a5e397d96f215b62641755d2a59b7\jetty-server-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-servlet\9.0.7.v20131107\f7d8ce6ecb2318b906ba4df1b8625ab2b34e305b\jetty-servlet-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-servlets\9.0.7.v20131107\bffeae9b9f75f53d3e5dc1bfd56725f67f2f67c0\jetty-servlets-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-http\9.0.7.v20131107\67060a59b426c76a2788ea5f4e19c1d3170ac562\jetty-http-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-json\3.0.1\6450c81c5f5b36a82fbb27a39ee3d9b7529a6770\metrics-json-3.0.1.jar;C:\Users\defaultUser\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar;C:\Users\defaultUser\.m2\repository\org\mortbay\jetty\jetty-util\6.1.26\jetty-util-6.1.26.jar;C:\Users\defaultUser\.m2\repository\org\mortbay\jetty\servlet-api\2.5-20081211\servlet-api-2.5-20081211.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.json\json\20090211\c183aa3a2a6250293808bba12262c8920ce5a51c\json-20090211.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\net.minidev\json-smart\1.1.1\24a2f903d25e004de30ac602c5b47f2d4e420a59\json-smart-1.1.1.jar;C:\Users\defaultUser\.m2\repository\org\apache\httpcomponents\httpcore\4.2.2\httpcore-4.2.2.jar;C:\Users\defaultUser\.m2\repository\commons-codec\commons-codec\1.6\commons-codec-1.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\javax.validation\validation-api\1.1.0.Final\8613ae82954779d518631e05daa73a6a954817d5\validation-api-1.1.0.Final.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.jboss.logging\jboss-logging\3.1.1.GA\7fb1a7eb7ff1d15cac1802510fee65c7ca31a869\jboss-logging-3.1.1.GA.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml\classmate\1.0.0\434efef28c81162b17c540e634cffa3bd9b09b4c\classmate-1.0.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\javax.el\javax.el-api\2.2.5\370140e991eefb212a6d6baedbce585f00ef76e0\javax.el-api-2.2.5.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.codahale.metrics\metrics-annotation\3.0.1\999be28942c85b95b70d34acba466cfe5cbd24a6\metrics-annotation-3.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.jaxrs\jackson-jaxrs-base\2.3.2\14adfd8e7d9caacd97e1c0627486dd1cc70ff211\jackson-jaxrs-base-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.module\jackson-module-jaxb-annotations\2.3.2\228f4ed947cf3403c5f4315143b6c372c28e90f\jackson-module-jaxb-annotations-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-io\9.0.7.v20131107\512e9d2e088ae7c70c4a68381423cb68b9ed42d6\jetty-io-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-security\9.0.7.v20131107\23e7943c18e5c340455a40876ce5093c980c210\jetty-security-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.eclipse.jetty\jetty-continuation\9.0.7.v20131107\4a26ae30011d933ac2c5f8d840e3374bc0d136eb\jetty-continuation-9.0.7.v20131107.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.3.2\c75edc740a6d8cb1cef6fa82fa594e0bce561916\jackson-databind-2.3.2.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.3.0\f5e853a20b60758922453d56f9ae1e64af5cb3da\jackson-annotations-2.3.0.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\16.0.1\5fa98cd1a63c99a44dd8d3b77e4762b066a5d0c5\guava-16.0.1.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.3.2\559b70ac8a0d5cad611da4223137a920147201ba\jackson-core-2.3.2.jar;C:\Users\defaultUser\.gradle\wrapper\dists\gradle-1.12-bin\2qvnajdoo11hasdfkikjaci26k\gradle-1.12\lib\groovy-all-1.8.6.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\com.thilko.spring\gradle-springdoc-plugin\0.4\429f809d58ca47d4e23465949f138041dcd8cb55\gradle-springdoc-plugin-0.4.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-webmvc\4.0.0.RELEASE\a82202c4d09d684a8d52ade479c0e508d904700b\spring-webmvc-4.0.0.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-beans\4.0.0.RELEASE\97e97a04aede419679392176ec1df175d3e9a7a0\spring-beans-4.0.0.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-context\4.0.0.RELEASE\57586271e775982f8961e1e7e338447d4af1864c\spring-context-4.0.0.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-core\4.0.0.RELEASE\73b485e25b13a7a44b73a301fe6757c3cbad453e\spring-core-4.0.0.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-expression\4.0.0.RELEASE\199be03c976524b6427dff31078227bfc703400b\spring-expression-4.0.0.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-web\4.0.0.RELEASE\6ce2dda16a3c1581920fc17551f3ae17d26499aa\spring-web-4.0.0.RELEASE.jar;C:\Users\defaultUser\.gradle\caches\modules-2\files-2.1\org.springframework\spring-aop\4.0.0.RELEASE\cceb3e9510774b3f88b008a70c6a9aefb98d891f\spring-aop-4.0.0.RELEASE.jar;C:\Users\defaultUser\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;c:\content\build\classes\main;c:\content\build\resources\main c:\content\src\main\java\content\application\ContentApplication.java c:\content\src\main\java\content\application\ContentBundle.java c:\content\src\main\java\content\application\ContentConfiguration.java c:\content\src\main\java\content\application\ContentSpringContext.java c:\content\src\main\java\content\application\api\ProductsResource.java c:\content\src\main\java\content\application\api\StoreResource.java c:\content\src\main\java\content\application\domain\Product.java
11:40:28.622 [INFO] [org.gradle.api.internal.tasks.compile.jdk6.Jdk6JavaCompiler] Compiling with JDK Java compiler API.
11:40:29.322 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':content:generateSpringDoc'
11:40:29.322 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :content:generateSpringDoc (Thread[main,5,main]) completed. Took 0.747 secs.
`

**Comment by thilko** [comment]
The line I´ve meant is:

```
[DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -d c:\content\build -g -s c:\content\build -proc:only -processor 
```

Therefore the file should be generated in `c:\content\build`.
Are your spring mvc annotations (Controller, RequestMapping etc.) is living in one of the following classes?

```
c:\content\src\main\java\content\application\ContentApplication.java   
c:\content\src\main\java\content\application\ContentBundle.java
c:\content\src\main\java\content\application\ContentConfiguration.java
c:\content\src\main\java\content\application\ContentSpringContext.java
c:\content\src\main\java\content\application\api\ProductsResource.java
c:\content\src\main\java\content\application\api\StoreResource.java
c:\content\src\main\java\content\application\domain\Product.java
```

**Comment by thilko** [comment]
The issue with Java 7 is fixed, I will track the progress of the second bug in https://github.com/thilko/gradle-springdoc-plugin/issues/3.
